title: What's happen in your city
description: Este proyecto de visualización tiene la intención de interactuar con tu ciudad a través de herramientas de Google
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
